# Mergify configuration file
# https://doc.mergify.io/configuration.html
pull_request_rules:
  - name: automatic merge develop -> master
    conditions:
      # pull request is to master
      - base=master
      # pull request has label set by our create PR action
      - label=auto-pr
      # need to quote the condition to escape spaces
      # https://doc.mergify.io/conditions.html#status-check-name
      - "status-success=ci/circleci: docs-tests"
    actions:
      merge:
        method: merge
