// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  app: [{ type: 'autogenerated', dirName: 'app' }],
  api: [{ type: 'autogenerated', dirName: 'api' }],
  examples: [{ type: 'autogenerated', dirName: 'examples' }],
  faq: [{ type: 'autogenerated', dirName: 'faq' }],
}

module.exports = sidebars
