version: 2.1

orbs:
  cypress: cypress-io/cypress@4

executors:
  node-executor:
    resource_class: medium+
    docker:
      - image: cimg/node:22.23.1

commands:
  docs-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Docs Build
          command: npm run build


job-defaults: &job-defaults
  executor: node-executor
  working_directory: ~/repo

jobs:
  build:
    <<: *job-defaults
    steps:
      - docs-build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist/*
            - node_modules/*

  lint:
    <<: *job-defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

  unit-tests:
    <<: *job-defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Search / Algolia unit tests
          command: npm run test:search

  install-and-persist:
    executor:
      name: cypress/default
      node-version: 22.23.1
    resource_class: medium+
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-project-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - cypress-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Install Cypress binary
          command: npx cypress install
      - save_cache:
          key: npm-cache-project-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: cypress-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/Cypress
      - run:
          name: Build site for tests
          command: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache/Cypress
            - project

  run-tests-in-parallel:
    executor:
      name: cypress/default
      node-version: 22.23.1
    resource_class: large
    parallelism: 8
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          start-command: 'npm run serve'
          cypress-command: 'npx wait-on http://localhost:3000 && npx cypress run --parallel --record'

  release:
    <<: *job-defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker
      - run:
          name: Algolia Scraper
          command: |
            echo "Scraping..."
            ls
            node ./scripts/search/scrape-and-compare-algolia-index.mjs

workflows:
  build-and-test:
    jobs:
      - build
      - lint:
          name: "Lint JS/CSS/Markdown"
          requires:
            - build
      - unit-tests:
          name: "Unit Tests (Search/Algolia)"
          requires:
            - build
      - install-and-persist:
          name: Install & Persist To Workspace
      - run-tests-in-parallel:
          name: Run Tests in Parallel
          requires:
            - Install & Persist To Workspace
      - release:
          name: 'Run Algolia scraper'
          requires:
            - build
          filters:
            branches:
              only:
                - main
