name: "Documentation Request"
description: "Request for documentation to be added/altered"
labels: ["content: rewrite"]
body:
  - type: "markdown"
    attributes:
      value: |
        Thanks for filing a documentation request!

        If you have an idea for a new documentation topic, noticed that
        something is not properly documented, or feel that something is
        incorrect with the current documentation, you're in the right place!
  - type: "input"
    id: "subject"
    attributes:
      label: "Subject"
      description:
        "What is the subject (guides, api, plugins, examples, faq) of this request?"
      placeholder: "Guides"
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description:
        "What about the subject's documentation should be added or changed?"
      placeholder: "Add a usage example of RadioGroup in action"
    validations:
      required: true
